
INCLUDE=/home/dfarep/include
BINNAME=cutfield
SRCFILES=./cutfield.c
# /home/dfarep/share/gengetopt/getopt1.c /home/dfarep/share/gengetopt/getopt.c
CFLAGS=-I/home/jhinds/include -L/home/jhinds/lib -ansi -Wall -O2

build ::; gcc ${CFLAGS} -I${INCLUDE} -o ${BINNAME} ${SRCFILES}
