/************************************
  copyright 2005

 ************************************/

/** @file main.c
  * @brief just contains the main() function.
  *
  * generated by cgen.  http://home.thatbox.net/~k4thryn/code/cgen/
  */

#include "reorder_main.h"

/** @brief entry point into the application.
  * as this is a generated function, it just calls apropriate fucntions to
  * parse commandlines, may do some user-defined code from the argument table,
  * and calls user-defined function reorder(), which is where all the real
  * work will begin.
  * 
  * @param argc number of command-line arguments.
  * @param argv list of arguments.
  * 
  * @return 
  */
int main ( int argc, char *argv[] ){
	struct cmdargs args;

	parse_args ( argc, argv, &args );

	
	if ( args.help ){
		usage(argv[0]); exit(EXIT_HELP);
	}

	if ( args.version ){
		version(); exit(1);
	}


	return reorder( &args, argc, argv, optind );
}

