/************************************
  copyright 2005

 ************************************/

/** @file reorder_main.h
 *  @brief defines structure to hold command-line arguments and protypes
 *  some functions.
 *
 *  generated by cgen.  http://home.thatbox.net/~k4thryn/code/cgen/
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#ifndef REORDER_MAIN_H
#define REORDER_MAIN_H

/* user-defined things in arg table */
#include "reorder.h"
/* end user-defined things */

/** exit code to use when invoked with usage() or version(). */
#define EXIT_HELP 1
/** exit code to use when everything was okay. */
#define EXIT_OKAY 0
/** exit code to use when there was an i/o-related error. */
#define EXIT_FILE_ERR -1
/** exit code to use when there was an error allocating memory. */
#define EXIT_MEM_ERR -2

/** current version of the application. */
#define APPLICATION_VERSION "0.1"
/** short description of what the app does. */
#define APPLICATION_DESCRIPTION "swaps columns in a delimited flat file"

/** structure to hold commandline options & arguments.
 */
struct cmdargs {
	int help;	/**< @brief print this message and exit */
	int version;	/**< @brief print version info and exit */
	int verbose;	/**< @brief print verbose messages during execution */
	char *delim;	/**< @brief specifies delimiting string */
	char *swap;	/**< @brief specifies two fields to swap (ex: -s 1,3) */
	char *move;	/**< @brief specifies a field to move to a new position (ex: -s 3,1) */
	char *fields;	/**< @brief specifies fields to use to create a new string (ex: -f 3,4,1,5,2) */
};


/** parses commandline arguments and puts the info into a cmdargs struct.
 * @param argc number of arguments
 * @param argv array of argument strings
 * @param args structure to hold the parsed options & arguments
 */
void parse_args ( int, char **, struct cmdargs *);

/** prints application help information.
 * @param bin application name as invoked on the commandline
 */
void usage ( char * );

/** @brief prints application version.
  */
void version ( void );

/** @brief beginning of primary application logic section called by main().
  * 
  * @param args contains the parsed cmd-line options & arguments.
  * @param argc number of cmd-line arguments.
  * @param argv list of cmd-line arguments
  * @param optind index of the first non-option cmd-line argument.
  * 
  * @return exit status for main() to return.
  */
int reorder( struct cmdargs *args, int argc, char *argv[], int optind );

#endif
