/************************************
  copyright 2005

 ************************************/

/** @file usage.c
 *  @brief contains functions for parsing arguments and printing usage info.
 *
 *  generated by cgen.  http://home.thatbox.net/~k4thryn/code/cgen/
 */


#include "reorder_main.h"

/** prints application help information.
 * @param bin application name as invoked on the commandline
 */
void usage( char *bin ) {
	fprintf(stderr, "\nreorder: swaps columns in a delimited flat file\n");
	fprintf(stderr, "\nusage: %s <options> [file(s)] \n", bin);
	fprintf(stderr, "options:\n");
	fprintf(stderr, "\t-h, --help\tprint this message and exit\n");
	fprintf(stderr, "\t-V, --version\tprint version info and exit\n");
	fprintf(stderr, "\t-v, --verbose\tprint verbose messages during execution\n");
	fprintf(stderr, "\t-d, --delim <delim>\tspecifies delimiting string\n");
	fprintf(stderr, "\t-s, --swap <swap>\tspecifies two fields to swap (ex: -s 1,3)\n");
	fprintf(stderr, "\t-m, --move <move>\tspecifies a field to move to a new position (ex: -s 3,1)\n");
	fprintf(stderr, "\t-f, --fields <fields>\tspecifies fields to use to create a new string (ex: -f 3,4,1,5,2)\n");
	fprintf(stderr, "\nthe fields param is exclusive of swap and move - if -f and -m or -s are\nspecified, only -f will be used.\n\nexample: reorder -d : -s 1,3 -m 2,4 /etc/passwd\n\nwould swap fields 1 and 3, and then would move field 2 to position 4.");
	printf("\n\n");
	return;
} 

/* this won't be used outside of this file */
void init_cmdargs( struct cmdargs * );

#include <getopt.h>

/** long option structure list */
static struct option long_options[] = {
	{"help", no_argument, 0, 'h'},
	{"version", no_argument, 0, 'V'},
	{"verbose", no_argument, 0, 'v'},
	{"delim", required_argument, 0, 'd'},
	{"swap", required_argument, 0, 's'},
	{"move", required_argument, 0, 'm'},
	{"fields", required_argument, 0, 'f'},
	{0, 0, 0, 0}
};

/** parses commandline arguments and puts the info into a cmdargs struct.
 * @param argc number of arguments
 * @param argv array of argument strings
 * @param args structure to hold the parsed options & arguments
 */
void parse_args ( int argc, char **argv, struct cmdargs *args){
	int c, option_index=0;

	init_cmdargs(args);

	while( (c = getopt_long(argc, argv, "hVvd:s:m:f:", long_options, &option_index)) != -1 ){
		switch (c) {
			case '0':
				if( long_options[option_index].flag != 0 )
					break;
			case 'h':
				args->help = 1;
				break;
			case 'V':
				args->version = 1;
				break;
			case 'v':
				args->verbose++;;
				break;
			case 'd':
				args->delim = optarg;
				break;
			case 's':
								if( pushswap(optarg, REORDER_TYPE_SWAP ) != 0 ){
					fprintf(stderr, "invalid fields in \"-s %s\"\n", optarg);
					exit(EXIT_HELP);
				}
;
				break;
			case 'm':
								if( pushswap(optarg, REORDER_TYPE_MOVE ) != 0 ){
					fprintf(stderr, "invalid fields in \"-s %s\"\n", optarg);
					exit(EXIT_HELP);
				}
;
				break;
			case 'f':
				args->fields = optarg;
				break;
			default: break;
		}
	}
	return;
}


/** @brief initializes all elements in the cmdargs struct to NULL or 0.
 *  @param args pointer to the argument structure to be cleared out.
 */
void init_cmdargs( struct cmdargs *args ){
	/* this set all pointers to null, int values to 0 */
	memset( args, 0, sizeof(struct cmdargs) );
}

/** @brief prints application version.
  */
void version ( void ){
	fprintf(stderr, "%s\n", APPLICATION_VERSION);
}

